### ISSUE TITLE
Plugin could not be installed via Marketplace on Eclipse 2018-09

### ISSUE THREAD

**Issue by ibruell** [AgileReview-Project/AgileReview-Legacy-Plugin#29]
Installing AgileReview via MarketPlace results in the following error:

org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://www.agilereview.org/update/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:398)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:353)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:244)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:121)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:106)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:84)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by bardyguillaume** [comment]
Hi,
I have the error too on Eclipse Photon (I think there is the error with others eclipse version too)
Trying browsing the url we have : 
404 - File not found

Thanks

**Comment by maybeec** [comment]
Could you please try again? Should be fixed now.

**Comment by bardyguillaume** [comment]
Thanks a lot @maybeec I check it works again for my issue
